apiVersion: extensions / v1beta1
kind: Deployment
metadata:
 name: mongodb3
namespace: production
spec:
 replicas: 1
template:
 metadata:
 labels:
 k8s-app: mongodb3
spec:
 containers:
 -name: mongodb3
image: dr.xenonstack.com: 5050 / mongo: v3 .0
imagePullPolicy: "IfNotPresent"
ports:
 -containerPort: 27017
volumeMounts:
 -mountPath: /data/db
name: mongodisk1
volumes:
 -name: mongodisk1
glusterfs:
 endpoints: glusterfs - cluster
path: mongodb - disk
readOnly: false
