apiVersion: extensions / v1beta1
kind: Deployment
metadata:
 name: rocketchat
namespace: production
spec:
 replicas: 1
template:
 metadata:
 labels:
 k8s-app: rocketchat
spec:
 containers:
 -name: rocketchat
image: dr.xenonstack.com: 5050 / rocketchat: v1 .0
imagePullPolicy: "IfNotPresent"
ports:
 -containerPort: 3000
env:
 -name: MONGO_URL
value: "mongodb://mongodb3:27017/rocketchat"

